```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}


library(gridExtra)

library(tidyverse)
library(ggtext)
library(ggrepel)
library(grid)
library(ggforce)
library(showtext)
library(magick)
library(googlesheets4)
data<- read_sheet('https://docs.google.com/spreadsheets/d/1gANfa3d6Y4EGBuODZGbW4m6yHjCOSovfzkFLxvRhBrM/edit?usp=sharing')

data$region <- factor(data$region, levels = unique(data$region))


```
```{r}

picture <- image_graph(width = 760, height = 540)
annotation_custom2 <- 
function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn, 
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}

font_add(family="Open", regular="OpenSans-Bold.ttf")
showtext_auto()
pop_colors<- c('#b6a6b8','#cecfdb','#b6a6b8','#cecfdb','#b6a6b8','#cecfdb','#b6a6b8','#cecfdb','#f3b343','#7ba539','#d8252e','#e6e154','#3e6dbe')
ggplot(data=data, aes(x=" ", y=rev(value), group=year, fill=rev(region))) +
         geom_bar(stat = "identity", color='black', size = .3) +
         coord_polar("y", start=0) + 
         facet_grid(.~ year) +theme_void()+ scale_fill_manual(values=pop_colors)+
  labs(caption= "Source: US Energy and Information Administration.")+
  theme(legend.position = "none",
        plot.margin =  unit(c(6.5,2.2,2.8,2.2), "cm"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid  = element_blank(),
        strip.text.x = element_blank(),
        panel.spacing = unit(8, "lines"),
        plot.title = element_textbox(vjust =125),
        plot.caption= element_text(vjust=-20, hjust = -.13, size = 13))
dev.off()
img <- image_draw(picture)
 polygon(c(0, 760, 760, 0), c(0, 0, 50, 50), border = "#6D7166", col = "#6D7166")+
     text(81, 28, "STIMATED", family = "Open", cex = 1.4, col = "white")+
   text(30, 25, "E", family = "Open", cex = 2.2, col = "white")+
   text(137, 25, "S", family = "Open", cex = 2.2, col = "white")+
   text(167, 28, "HARE", family = "Open", cex = 1.4, col = "white")+
   text(210, 28, "OF", family = "Open", cex = 1.4, col = "white")+
   
text(37, 90, substitute(paste(bold('2000'))), family = "Text", cex = 1.3, col = "black")+
   text(400, 90, substitute(paste(bold('2010'))), family = "Text", cex = 1.3, col = "black")+
   text(45 , 110, substitute(paste(italic('Percent'))), family = "Text", cex = 1.15, col = "black")+
   text(412, 110, substitute(paste(italic('Percent'))), family = "Text", cex = 1.15, col = "black")+
   text(8, 155, "Non-OPEC\nMiddle East, 3", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(9, 185, "Africa, 4", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(10, 225, "Latin America, 5", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(10, 255, "Europe, 8", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(8.8, 305, "Asia-Pacific,\n9", family = "Text", cex = 1.13, col = "black", pos=4)+
   text(8, 363, "Former", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(8, 378, "Soviet", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(8, 393, "Union, 10", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(172, 433, "North America,", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(172, 448, "20", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(278, 380, "Non-Gulf", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(278, 394, "OPEC, 13", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(294, 300, "Other Gulf", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(294, 313, "OPEC, 8", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(288, 275, substitute(paste(bold("Iraq, 3"))), family = "Text", cex = 1.35, col = "red", pos=4)+
   text(270, 245, "Iran, 5", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(235, 215, "Saudi Arabia, 12", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(217, 162, "Other, 1", family = "Text", cex = 1.25, col = "black", pos=4)+
   
   text(383, 155, "Non-OPEC\nMiddle East, 2", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(384, 183, "Africa, 4", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(382, 205, "Latin America,", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(382, 220, "5", family = "Text", cex = 1.2, col = "black", pos=4)+
   text(382, 250, "Europe, 7", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(380, 310, "Asia-Pacific,\n7", family = "Text", cex = 1.15, col = "black", pos=4)+
   text(382, 355, "Former", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(382, 370, "Soviet", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(382, 385, "Union, 12", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(546, 435, "North America,", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(546, 450, "17", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(652, 382, "Non-Gulf", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(652, 396, "OPEC, 14", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(668, 322, "Other Gulf", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(668, 335, "OPEC, 8", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(667, 295, substitute(paste(bold("Iraq, 4"))), family = "Text", cex = 1.35, col = "red", pos=4)+
   text(655, 260, "Iran, 4", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(619, 218, "Saudi Arabia, 15", family = "Text", cex = 1.25, col = "black", pos=4)+
   text(631, 163, "Other, 1", family = "Text", cex = 1.25, col = "black", pos=4)+
   
   segments(x0=110, x1=165, y0=160, y1=160, lwd = 1, lty = "solid")+
   segments(x0=75, x1=140, y0=182, y1=182, lwd = 1, lty = "solid")+
   segments(x0=140, x1=160, y0=182, y1=217, lwd = 1, lty = "solid")+
   segments(x0=165, x1=180, y0=160, y1=210, lwd = 1, lty = "solid")+
   segments(x0=20, x1=350, y0=100, y1=100, lwd = 2, lty = "solid")+
   segments(x0=383, x1=740, y0=100, y1=100, lwd = 2, lty = "solid")+
   segments(x0=85, x1=106, y0=255, y1=255, lwd = 1, lty = "solid")+
   segments(x0=65, x1=100, y0=363, y1=363, lwd = 1, lty = "solid")+
   segments(x0=190, x1=213, y0=162, y1=162, lwd = 1, lty = "solid")+
   segments(x0=190, x1=189.5, y0=162, y1=210, lwd = 1, lty = "solid")+
   segments(x0=488, x1=540, y0=160, y1=160, lwd = 1, lty = "solid")+
   segments(x0=540, x1=555, y0=160, y1=211, lwd = 1, lty = "solid")+
   segments(x0=633, x1=565, y0=163, y1=163, lwd = 1, lty = "solid")+
   segments(x0=565, x1=564, y0=163, y1=211, lwd = 1, lty = "solid")+
   segments(x0=455, x1=486, y0=250, y1=250, lwd = 1, lty = "solid")+
   segments(x0=484, x1=496, y0=205, y1=205, lwd = 1, lty = "solid")+
   segments(x0=439, x1=470, y0=354, y1=354, lwd = 1, lty = "solid")+
   segments(x0=496, x1=510, y0=205, y1=225, lwd = 1, lty = "solid")+
   segments(x0=449, x1=520, y0=183, y1=183, lwd = 1, lty = "solid")+
   segments(x0=520, x1=535, y0=183, y1=215, lwd = 1, lty = "solid")
dev.off()
image_write(img, path = here::here("Data vis for Iraq's Petroleum and Gas Infrastructure", "Key.png"), format = "png")

#ggsave('hi.pdf', height  = 4.35)

```
