---
title: "Types of Iraqi Oil"
author: "Lauryn Davis"
date: "7/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
# I like this for coloring text: https://wilkelab.org/ggtext/
library(grid)
library(rlang)
library("ggtext")
```

```{r, fig.height= 5, fig.width= 9}

pop_colors = c("#010102" , "#1566ac","#ed1f02", "#e1eb00", "#8fa800" )
#black, blue, red, yellow, green

df<- data.frame(
  type_levels= c("Very Heavy","Light", "Medium", "Regular", "Heavy"),
  value= c(5,7,18,27,43), 
  Label= c("Very heavy\n(20),5", "Light (38 +), 7", "Medium\n(27 -33),\n18", "Regular (34 -37),\n27", "Heavy (20 -26),\n43"), 
  pop_colors = c("#010102" , "#1566ac","#ed1f02", "#e1eb00", "#8fa800" )
)

df

library(dplyr)
df <- df %>% 
  mutate(end = 2 * pi * cumsum(value)/sum(value),
         start = lag(end, default = 0),
         middle = 0.5 * (start + end),
         hjust = ifelse(middle > pi, 1, 0),
         vjust = ifelse(middle < pi/2 | middle > 3 * pi/2, 0, 1))
library(ggforce) # for 'geom_arc_bar'
ggplot(df)+ 
  geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = 1, r = 0,
                   start = start, end = end, fill = reorder(type_levels, value)))+
  geom_text(aes(x = 1.05 * sin(middle), y = 1.05 * cos(middle), label = Label,
                hjust = hjust, vjust = vjust)) +
  coord_fixed() +
  scale_x_continuous(limits = c(-1.5, 1.5),  # Adjust so labels are not cut off
                     name = "", breaks = NULL, labels = NULL) +
  scale_y_continuous(limits = c(-1.1, 1.1),    # Adjust so labels are not cut off
                     name = "", breaks = NULL, labels = NULL) + theme_classic()+ theme(axis.line=element_blank(),
                                  axis.text.x = element_blank(),
                                  axis.text.y= element_blank(),
                                  axis.title.x = element_blank(),
                                  axis.title.y= element_blank(),
                                  legend.position = "none") + scale_fill_manual(values= pop_colors)




```
```{r}
library(ggrepel)
df<- data.frame(
  type_levels= c("Very Heavy","Light", "Medium", "Regular", "Heavy"),
  value= c(5,7,18,27,43), 
  Label= c("Very heavy\n(20),5", "Light (38 +), 7", "Medium\n(27 -33),\n18", "Regular (34 -37),\n27", "Heavy (20 -26),\n43"), 
  pop_colors = c("#010102" , "#1566ac","#ed1f02", "#e1eb00", "#8fa800" )
)
df2<- df%>%
  mutate(csum = rev(cumsum(rev(value))), 
         pos = value/2 + lead(csum, 1),
         pos = if_else(is.na(pos), value/2, pos))
  
bp<- ggplot(df2, aes(x="", y=value, fill= reorder(type_levels, value)))+ 
  geom_bar(width=1, stat= "identity") +
  geom_text(aes(x=1.8, label=Label),
            position = position_stack(vjust=0.2))
pie<- (bp+ coord_polar("y", start=0) +  # Using ggtext + HTML syntax to color text
  # For some reason '\n' doesn't work here so I used <br> instead.
  labs(title = "<p><span style = 'font-size:11pt; color:#000000'><i>Percent</span></p>",
       subtitle = "<p><span style = 'font-size:11pt; color:#0c64a4'>Numbers in Parenthesis are American</p><p><span style= 'font-size 11pt; color: #0c64a4'> Petroleum Institute (API) degrees gravity.</span></p>",
       y = "",
       x = "",
       caption ="<p><span style = 'font-size:11pt; color:#000000'>Iraq markets two crude blends: 60 percent</p><p><span style = 'font-size:11pt; color:#000000'>of exports is Basrah Light
+ 
  theme_classic()
+ theme(axis.line=element_blank(),
                                  axis.text.x = element_blank(),
                                  axis.text.y= element_blank(),
                                  axis.title.x = element_blank(),
                                  axis.title.y= element_blank(),
                                  legend.position = "none",
                         plot.title= element_markdown(),
                         plot.subtitle = element_markdown())
+ scale_fill_manual(values= pop_colors))
pie

  

 
 
  
  
```
