---
title: "Crude Oil Production and Projections"
author: "Lauryn Davis"
date: "8/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtext)
library(ggrepel)
library(showtext)
library(grid)
```
```{r, fig.height= 4, fig.width= 7.5}
font_add(family="Open", regular= 	"OpenSans-Bold.ttf")
showtext_auto()
year_levels = c("60","60.5","61","61.5","62",'62.5','63','63.5','64','64.5','65','65.5','66','66.5','67','67.5','68','68.5','69','69.5','70','70.5','71','71.5','72','72.5','73','73.5','74','74.5','75','75.5','76','76.5','77','77.5','78','78.5','79','79.5','80','80.5','90','90.5','91','91.5','92','92.5','93')
x_label<- c("1980", "", "81", "", "82", "", "83", "","84", "", "85","", "86", "", "87", "", "88","", "89","", "90", "", "91", "", "92", "", "93", "", "94", "", "95", "", "96", "", "97","", "98","", "99", "", "2000", "", "01", "", "02", "", "03", "", "04")


data<- tibble(
 year_levels = c("60","60.5","61","61.5","62",'62.5','63','63.5','64','64.5','65','65.5','66','66.5','67','67.5','68','68.5','69','69.5','70','70.5','71','71.5','72','72.5','73','73.5','74','74.5','75','75.5','76','76.5','77','77.5','78','78.5','79','79.5','80','80.5','90','90.5','91','91.5','92','92.5','93'),
  amount= c(3.47,
1.79,
0.78,
0.99,
1.17,
0.83,
1.01,
1.15,
1.09,
1.24,
1.25,
1.56,
1.74,
1.70,
1.82,
2.25,
2.54,
2.66,
2.72,
2.92,
3.03,
0.84,
0.15,
0.28,
0.35,
0.39,
0.49,
0.49,
0.50,
0.53,
0.54,
0.54,
0.53,
0.59,
1.06,
1.21,
2.11,
2.40,
2.50,
2.54,
2.40,
2.50,
2.21,
2.40,
2.12,
1.92,
3.02,
3.28,
3.51)
)
```
```{r, fig.height= 4, fig.width= 7.5}
line<- ggplot(data) +
  geom_area(mapping = aes(x = year_levels, y = amount), fill = "#6D8E2C", color= "black", size= .2)+  scale_x_discrete(labels= x_label, expand=expansion(mult=c(.03,.0)))+ 
  scale_y_continuous(breaks = c(0,.5,1,1.5,2,2.5,3,3.5,4), limits= c(0,4), expand= expansion(mult=c(0,.18)))
line
theme<- line+theme_classic()+
  theme(legend.position= "none",
        axis.title = element_blank(),
        axis.ticks= element_blank(),
        axis.line.y= element_blank(),
        panel.grid.major.x= element_blank(),
        panel.grid.minor.x= element_blank(),
        panel.grid.major.y= element_line(color="black", size=.15),
        panel.grid.minor.y= element_blank(),
        plot.caption= element_markdown(hjust= 0),
        axis.text.y= element_blank(),
        plot.margin=unit(c(0,.5,.5,.5), "cm"),
        plot.background= element_rect(color="black"),
        plot.title= element_textbox_simple(family= "Open",size = 8, lineheight = 1, 
      width = grid::unit(7.58, "in"), # fixed width
      hjust = .45, # alignment of box relative to plot
      linetype = 0, # turn on border
      box.color = "black", # border color
      fill = "#6D7166", # background fill color
      r = grid::unit(0, "pt"), # radius for rounded corners
      padding = margin(0, 5, 7, 10), # padding around text inside the box
      margin = margin(0, 0, 0, 0)))+
  labs(caption= "<p><span style = 'font-size:10pt; color:#000000'><sup>a</sup>Adapted from published oil ministry plans (assumes no sanctions constraints).</p></span>",
       title= "<p><span style = 'font-size:16pt; color: #FFFFFF'>C</span><span style = 'font-size:11pt; color: #FFFFFF'>RUDE</span><span style = 'font-size:16pt; color: #FFFFFF'> O</span><span style = 'font-size:11pt; color: #FFFFFF'>IL</span><span style = 'font-size:16pt; color: #FFFFFF'> P</span><span style = 'font-size:11pt; color: #FFFFFF'>RODUCTION</span><span style = 'font-size:16pt; color: #FFFFFF'> A</span><span style = 'font-size:11pt; color: #FFFFFF'>ND</span><span style = 'font-size:16pt; color: #FFFFFF'> P</span><span style = 'font-size:11pt; color: #FFFFFF'>ROJECTIONS</span>")
theme
  
```

