---
title: "Iraqi Oil Exports Under Phases 9, 10, 11, 12, and 13"
author: "Lauryn Davis"
date: "9/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(googlesheets4)
library(ggrepel)
library(showtext)
library(grid)
 
```

```{r,fig.height= 10, fig.width= 16}
pop_colors <- (rep(c('#39553A'), 40))
iraq_data<- read_sheet('https://docs.google.com/spreadsheets/d/1Oegm5JgkLwkgHyIqE2-6j8TT6JvQ3gq61gB2FEXAxWk/edit?usp=sharing')
font_add(family="Open", regular= 	"OpenSans-Bold.ttf")
showtext_auto()
```
```{r, fig.height= 5, fig.width= 10}
Label= "<span style = 'font-size:9pt; color:#000000'><i><b>Phase 9</span>"  
Label1= "<span style = 'font-size:9pt; color:#000000'><i><b>Phase 10</span>"
Label2 = "<span style = 'font-size:9pt; color:#000000'><i><b>Phase 11</span>"
Label3 = "<span style = 'font-size:9pt; color:#000000'><i><b>Phase 12</span>"
Label4 = "<span style = 'font-size:9pt; color:#000000'><i><b>Phase 13</span>"

area<- (ggplot(iraq_data, 
       aes(x = year, y= value))+
   geom_rect(aes(xmin = 30, xmax = 51, ymin = 0, ymax = 3.5), 
            fill = "#E7E3FB", alpha=.02)+
     geom_rect(aes(xmin = 80, xmax = 104, ymin = 0, ymax = 3.5), 
            fill = "#E7E3FB", alpha=.02)+
  geom_bar(stat= 'identity', fill= '#37573E', width = .8)+ theme_classic()+ scale_x_discrete(expand= expansion(mult=c(.03,0))) +   scale_y_continuous(breaks = c(0,.5,1,1.5,2,2.5,3,3.5), limits= c(0,3.5), expand= expansion(mult=c(.15,.4)))+ 
  geom_line(aes(x= year, y= cumul_mean1, group =1), size=1, color='#c5494d'))
area
  new<- area +labs(title= "<p><span style = 'font-size:16pt; color: #FFFFFF'>I</span><span style = 'font-size:11pt; color: #FFFFFF'>RAQI</span><span style = 'font-size:16pt; color: #FFFFFF'> O</span><span style = 'font-size:11pt; color: #FFFFFF'>IL</span><span style = 'font-size:16pt; color: #FFFFFF'> E</span><span style = 'font-size:11pt; color: #FFFFFF'>XPORTS</span><span style = 'font-size:16pt; color: #FFFFFF'> U</span><span style = 'font-size:11pt; color: #FFFFFF'>NDER</span><span style = 'font-size:16pt; color: #FFFFFF'> P</span><span style = 'font-size:11pt; color: #FFFFFF'>HASES</span></span><span style = 'font-size:16pt; color: #FFFFFF'> 9,10,11,12</span><span style = 'font-size:11pt; color: #FFFFFF'> AND</span><span style = 'font-size:16pt; color: #FFFFFF'> 13</span><br><span style = 'font-size:10.5pt; color: #FFFFFF'>December 2000 Through January 2003</span>")+
       #subtitle= "<span style = 'font-size:8pt; color: #000000'>Weekly Average</span><br><span style = 'font-size:8pt; color: #000000'>Cumulatice average within phase</span>")+
  theme(plot.title= element_textbox_simple(family= "Open",size = 8.2, lineheight = 1, 
      width = grid::unit(10.1, "in"), # fixed width
      hjust = .45, # alignment of box relative to plot
      linetype = 0, # turn on border
      box.color = "black", # border color
      fill = "#6D7166", # background fill color
      r = grid::unit(0, "pt"), # radius for rounded corners
      padding = margin(0, 5, 7, 10), # padding around text inside the box
      margin = margin(-0, 0, 0, 0)),
      #plot.subtitle=  element_textbox_simple(size= 5, lineheight = 2, 
      #width = grid::unit(2.3, "in"), # fixed width
      #hjust = 0,
      #linetype = 1, # turn on border
      #box.color = "black", # border color
      #fill = "white", # background fill color
      #r = grid::unit(0, "pt"), # radius for rounded corners
      #padding = margin(10, 5, 7, 10), # padding around text inside the box
      #margin = margin(.5, .5, 5, 0)),
    legend.position= "none",                                             
        axis.line.x=element_blank(),                                                                       
        axis.title = element_blank(),
        axis.ticks.x= element_blank(),
        axis.ticks.y= element_blank(),
        axis.line.y= element_blank(),
        panel.grid.major.x= element_blank(),
        panel.grid.minor.x= element_blank(),
        panel.grid.major.y= element_line(color="black", size=.15),
        panel.grid.minor.y= element_blank(),
        axis.text.x= element_blank(),
        axis.text.y = element_blank(),
   plot.margin=unit(c(0,.5,.5,.5), "cm"),
        plot.background= element_rect(color="black"))

```
```{r, fig.height= 5, fig.width= 10}
# y axis custom breaks
final<- new +
annotation_custom(grob = grid::textGrob(label = "0", hjust=0, gp=gpar(col="black", cex=.8)),xmin = -2, xmax = -2, ymin = -.1, ymax = -.1)+
  annotate(geom="text", x=-1.9, y=.4, label=".5",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=.9, label="1.0",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=1.4, label="1.5",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=1.9, label="2.0",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=2.4, label="2.5",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=2.9, label="3.0",
              color="black", size= 3.8)+
  annotate(geom="text", x=-1.3, y=3.4, label="3.5",
              color="black", size= 3.8)+
#X-Axis custom breaks
  annotation_custom(grob = grid::textGrob(label = "Dec", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 1.1, xmax = 1.1, ymin = -.1, ymax = -.1)+
  annotation_custom(grob = grid::textGrob(label = "Jan", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 5, xmax = 5, ymin = -.1, ymax = -.1)+
  annotation_custom(grob = grid::textGrob(label = "Feb", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 9.3, xmax = 9.3, ymin = -.1, ymax = -.1)+
  annotation_custom(grob = grid::textGrob(label = "Mar", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 14.02, xmax = 14.02, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Apr", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 17.21, xmax = 19.21, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "May", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 22.42, xmax = 22.42, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Jun", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 27.11, xmax = 27.11, ymin = -.1, ymax = -.1)+
     annotation_custom(grob = grid::textGrob(label = "Jul", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 31.11, xmax = 32.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Aug", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 34.11, xmax = 36.11, ymin = -.1, ymax = -.1)+
     annotation_custom(grob = grid::textGrob(label = "Sep", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 39.11, xmax = 41.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Oct", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 44.11, xmax = 44.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Nov", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 48.11, xmax = 48.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Dec", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 53.11, xmax = 53.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Jan", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 57.11, xmax = 57.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Feb", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 61.11, xmax = 61.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Mar", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 65.5, xmax = 65.5, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Apr", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 70.11, xmax = 70.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "May", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 74.8, xmax = 74.8, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Jun", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 79.11, xmax = 79.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Jul", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 83.11, xmax = 83.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Aug", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 87.11, xmax = 87.11, ymin = -.1, ymax = -.1)+
 annotation_custom(grob = grid::textGrob(label = "Sep", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 91.11, xmax = 91.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Oct", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 95.11, xmax = 95.11, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Nov", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 99.5, xmax = 99.5, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Dec", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 104.5, xmax = 104.5, ymin = -.1, ymax = -.1)+
   annotation_custom(grob = grid::textGrob(label = "Jan", hjust=0, gp=gpar(col="black", cex=.7)),xmin = 109.11, xmax =109.11, ymin = -.1, ymax = -.1)+
annotation_custom(grob = grid::textGrob(label = "Iraqi surcharges continue; first\neported in late 2000", hjust=0, gp=gpar(col="black", cex=.7, lineheight=1, fontface= "italic")),xmin = 5, xmax =5, ymin = 3.75, ymax = 3.75)+
  annotation_custom(grob = grid::textGrob(label = "UN begins retreoactove\npricing policy in late 2001;\nIraqi exports drop over\nPhases 11 and 12", hjust=0, gp=gpar(col="black", cex=.7, lineheight=1, fontface='italic')),xmin =44, xmax =44, ymin = 3.9, ymax = 3.9)+
  annotation_custom(grob = grid::textGrob(label = "Million\n b/d", hjust=0, gp=gpar(col="black", cex=.7, lineheight=1, fontface='italic')),xmin =-2.5, xmax =-2.5, ymin = 3.7, ymax = 3.7)+
#Sector Labels
geom_richtext(aes(x= 12.5, y=3.3, label=Label, size=4.5), fill= NA, label.color=NA)+
  geom_richtext(aes(x= 41, y=3.3, label=Label1, size=4.5), fill= NA, label.color=NA)+
  geom_richtext(aes(x= 66.5, y=3.3, label=Label2, size=4.5), fill= NA, label.color=NA)+
  geom_richtext(aes(x= 91.5, y=3.3, label=Label3, size=4.5), fill= NA, label.color=NA)+
  geom_richtext(aes(x= 107.5, y=3.3, label=Label4, size=4.5), fill= NA, label.color=NA)
 ggsave('final.pdf') 

```

