---
title: "Figure 4"
author: "lauryn davis"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(googlesheets4)
library(ggrepel)
library(showtext)
library(extrafont)
library(grid)
library(magick)
```
```{r}
type_levels <- c('one')
year_levels <- c(1860,1859,1858,1857,1856,1855,1854,1853,1852,1851,1850,1849,1848,1847,1846,1845,1844,1842,1841,1840,1839,1838,1837,1836,1835,1834,1833,1832,1831,1830,1829,1828,1827,1826,1825,1824,1823,1822,1821,1820,1819,1818,1817,1816,1815,1814,1813,1812,1811,1810,1809,1808,1807,1806,1805,1804,1803,1802,1801,1800,1799,1798,1797,1796,1795,1794,1793,1792)
year_levels1<- rev(year_levels)
pop_colors<- c("#d69083")
firstbar <- tibble(
  vote_type = rep(type_levels, 68),
  # Need to rep the pop_group within each vote_type
  pop_group = rep(year_levels,c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)),
  amount = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  fill = rep(pop_colors, 68))
picture <- image_graph(width = 570, height = 870)
annotation_custom2 <- 
function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax =Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn, 
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}
ggplot(firstbar, aes(x = pop_group, 
                      y = amount, fill=fill, label=''))+
  geom_col(color = "black", size= .3, width=1)+ 
  coord_flip()+
theme_classic()+
    theme( panel.grid = element_blank(),
           panel.grid.major = element_blank(),
           panel.grid.minor = element_blank(),
           axis.ticks = element_blank(),
           axis.line.y = element_blank(),
           axis.text.y= element_text(color='black', family='Rokkitt', size=12, margin = unit(0,'cm')),
           axis.text.x=element_blank(),
           axis.title=element_blank(),
           axis.line.x = element_blank(),
           legend.position='none',
           plot.margin = unit(c(.5,1,.5,1.2), "cm")) + scale_y_continuous(limits= c(0,101), expand=c(0,0)) + scale_x_discrete(position='top',expand=c(0,3))
dev.off()
img <- image_draw(picture)
 
 polygon(c(30.7, 538, 550, 19.1), c(850, 850, 840, 840), border = "black", col = "#d69083")+
   polygon(c(19.1, 550, 552, 16), c(840, 840, 830, 830), border = "black", col = "#d69083")+
   polygon(c(16, 552, 561, 10), c(830, 830, 820, 820), border = "black", col = "#d69083")+
   polygon(c(10, 561, 570, 1.7), c(820, 820, 810, 810), border = "black", col = "#d69083")+
   polygon(c(1.7, 570, 560, 10), c(810, 810, 800, 800), border = "black", col = "#d69083")+
   polygon(c(10, 560, 473, 101), c(800, 800, 790, 790), border = "black", col = "#d69083")+
   polygon(c(101, 473, 399, 169), c(790, 790, 780, 780), border = "black", col = "#d69083")+
   polygon(c(169, 399, 340, 230), c(780, 780, 770, 770), border = "black", col = "#d69083")+
   polygon(c(230, 340, 294, 276), c(770, 770, 760, 760), border = "black", col = "#d69083")+
   polygon(c(276, 294, 291, 278), c(760, 760, 750, 750), border = "black", col = "#d69083")+
   polygon(c(278, 291, 289.5, 279), c(750, 750, 740, 740), border = "black", col = "#d69083")+
    polygon(c(279, 289.5, 288, 280), c(740, 740, 730, 730), border = "black", col = "#d69083")+
   polygon(c(280, 288, 287, 280.6), c(730, 730, 720, 720), border = "black", col = "#d69083")+
   polygon(c(280.6, 287, 286, 281), c(720, 720, 710, 710), border = "black", col = "#d69083")+
   polygon(c(281, 286, 289, 279), c(710, 710, 700, 700), border = "black", col = "#d69083")+
   polygon(c(279, 289, 290, 277), c(700, 700, 690, 690), border = "black", col = "#d69083")+
   polygon(c(277, 290, 290, 277), c(690, 690, 680, 680), border = "black", col = "#d69083")+
   polygon(c(277, 290, 290, 276), c(680, 680, 670, 670), border = "black", col = "#d69083")+
   polygon(c(276, 290, 290, 276), c(670, 670, 660, 660), border = "black", col = "#d69083")+
   polygon(c(276, 290, 290, 276), c(660, 660, 650, 650), border = "black", col = "#d69083")+
    polygon(c(276, 290, 289, 277), c(650, 650, 640, 640), border = "black", col = "#d69083")+
   polygon(c(277, 289, 288, 278.5), c(640, 640, 630, 630), border = "black", col = "#d69083")+
   polygon(c(278.5, 288, 287, 279), c(630, 630, 620, 620), border = "black", col = "#d69083")+
   polygon(c(279, 287, 284, 282), c(620, 620, 610, 610), border = "black", col = "#d69083")+
   polygon(c(282, 284, 285, 281), c(610, 610, 600, 600), border = "black", col = "#d69083")+
   polygon(c(281, 285, 285.5, 280), c(600, 600, 590, 590), border = "black", col = "#d69083")+
   polygon(c(280, 285.5, 286, 279), c(590, 590, 580, 580), border = "black", col = "#d69083")+
    polygon(c(279, 286, 284, 281), c(580, 580, 570, 570), border = "black", col = "#d69083")+
   polygon(c(281, 284, 283.5, 281.5), c(570, 570, 560, 560), border = "black", col = "#d69083")+
    polygon(c(281.5, 283.5, 282, 282), c(560, 560, 550, 550), border = "black", col = "#d69083")+
   polygon(c(282, 282, 282, 282), c(550, 550, 540, 540), border = "black", col = "#d69083")+
   polygon(c(282, 282, 283, 281), c(540, 540, 530, 530), border = "black", col = "#d69083")+
    polygon(c(281, 283, 282, 282), c(530, 530, 520, 520), border = "black", col = "#d69083")+
   polygon(c(282, 282, 282, 282), c(520, 520, 510, 510), border = "black", col = "#d69083")+
    polygon(c(282, 282, 282, 282), c(510, 510, 500, 500), border = "black", col = "#d69083")+
   polygon(c(282, 282, 283, 281), c(500, 500, 490, 490), border = "black", col = "#d69083")+
   polygon(c(281, 283, 285, 279), c(490, 490, 480, 480), border = "black", col = "#d69083")+
   polygon(c(279, 285, 286, 278), c(480, 480, 470, 470), border = "black", col = "#d69083")+
    polygon(c(278, 286, 287, 277), c(470, 470, 460, 460), border = "black", col = "#d69083")+
   polygon(c(277, 287, 288, 275), c(460, 460, 450, 450), border = "black", col = "#d69083")+
    polygon(c(275, 288, 289, 273), c(450, 450, 440, 440), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(440, 440, 430, 430), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(430, 430, 420, 420), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(420, 420, 410, 410), border = "black", col = "#d69083")+
   polygon(c(273, 289, 289, 273), c(410, 410, 400, 400), border = "black", col = "#d69083")+
   polygon(c(273, 289, 291, 272), c(400, 400, 390, 390), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(390, 390,380, 380), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(380, 380, 370, 370), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(370, 370, 360, 360), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(360, 360, 350, 350), border = "black", col = "#d69083")+
   polygon(c(272, 291, 291, 272), c(350, 350, 340, 340), border = "black", col = "#d69083")+
   polygon(c(272, 291, 292, 270), c(340, 340, 330, 330), border = "black", col = "#d69083")+
   polygon(c(270, 292, 293, 269), c(330, 330, 320, 320), border = "black", col = "#d69083")+
   polygon(c(269, 293, 292, 270), c(320, 320, 310, 310), border = "black", col = "#d69083")+
   polygon(c(270, 292, 290, 271), c(310, 310, 300, 300), border = "black", col = "#d69083")+
   polygon(c(271, 290, 288, 272), c(300, 300, 290, 290), border = "black", col = "#d69083")+
    polygon(c(272, 288, 286, 275), c(290, 290, 280, 280), border = "black", col = "#d69083")+
   polygon(c(275, 286, 284, 277), c(280, 280, 270, 270), border = "black", col = "#d69083")+
   polygon(c(277, 284, 285, 276), c(270, 270, 260, 260), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(260, 260, 250, 250), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(250, 250, 240, 240), border = "black", col = "#d69083")+
   polygon(c(276, 285, 285, 276), c(240, 240, 230, 230), border = "black", col = "#d69083")+
   polygon(c(276, 285, 288, 273), c(230, 230, 220, 220), border = "black", col = "#d69083")+
   polygon(c(273, 288, 288, 273), c(220, 220, 210, 210), border = "black", col = "#d69083")+
   polygon(c(273, 288, 290, 270), c(210, 210, 200, 200), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(200, 200, 190, 190), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(190, 190, 180, 180), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(180, 180, 170, 170), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(170, 170, 160, 160), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(160, 160, 150, 150), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(150, 150, 140, 140), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(140, 140, 130, 130), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(130, 130, 120, 120), border = "black", col = "#d69083")+
   polygon(c(270, 290, 290, 270), c(130, 130, 120, 120), border = "black", col = "#d69083")+
   polygon(c(270, 290, 289, 270), c(120, 120, 110, 110), border = "black", col = "#d69083")+
   polygon(c(270, 289, 289, 270), c(110, 110, 100, 100), border = "black", col = "#d69083")+
    polygon(c(270, 289, 289, 270), c(100, 100, 90, 90), border = "black", col = "#d69083")+
    polygon(c(270, 289, 289, 271), c(90, 90, 80, 80), border = "black", col = "#d69083")+
   polygon(c(271, 289, 289, 271), c(80, 80, 70, 70), border = "black", col = "#d69083")+
   
   text(45,851, substitute(bold("1870")), cex = .9, col = "black", family = 'Rokkitt')
dev.off()
image_write(img, path = here::here('Walker Francis', "save3.png"), format = "png")



```